In [6]:
import pandas as pd
import os
import numpy as np
import cv2

In [7]:
# File name for the metadata to use in app.py
DATASET = 'train_data/'
METADATA_FILE = DATASET + 'labels.csv'
# ordering of columns in BOTH this file and app.py
YOLO_ORDER = ['label', 'x', 'y', 'w', 'h', 'image']
APP_ORDER = ['label', 'xmin', 'ymin', 'xmax', 'ymax', 'image']

In [12]:
# list of image names
image_files = sorted([x for x in os.listdir(DATASET + 'obj/') if x[-4:] == '.jpg'])
label_files = sorted([x for x in os.listdir(DATASET + 'obj/') if x[-4:] == '.txt'])

for i in zip(image_files, label_files):
    print(i)

('neg_1.jpg', 'neg_1.txt')
('neg_10.jpg', 'neg_10.txt')
('neg_100.jpg', 'neg_100.txt')
('neg_1000.jpg', 'neg_1000.txt')
('neg_1001.jpg', 'neg_1001.txt')
('neg_1002.jpg', 'neg_1002.txt')
('neg_1003.jpg', 'neg_1003.txt')
('neg_1004.jpg', 'neg_1004.txt')
('neg_1005.jpg', 'neg_1005.txt')
('neg_1006.jpg', 'neg_1006.txt')
('neg_1007.jpg', 'neg_1007.txt')
('neg_1008.jpg', 'neg_1008.txt')
('neg_1009.jpg', 'neg_1009.txt')
('neg_101.jpg', 'neg_101.txt')
('neg_1010.jpg', 'neg_1010.txt')
('neg_1011.jpg', 'neg_1011.txt')
('neg_1012.jpg', 'neg_1012.txt')
('neg_1013.jpg', 'neg_1013.txt')
('neg_1014.jpg', 'neg_1014.txt')
('neg_1015.jpg', 'neg_1015.txt')
('neg_1016.jpg', 'neg_1016.txt')
('neg_1017.jpg', 'neg_1017.txt')
('neg_1018.jpg', 'neg_1018.txt')
('neg_1019.jpg', 'neg_1019.txt')
('neg_102.jpg', 'neg_102.txt')
('neg_1020.jpg', 'neg_1020.txt')
('neg_1021.jpg', 'neg_1021.txt')
('neg_1022.jpg', 'neg_1022.txt')
('neg_1023.jpg', 'neg_1023.txt')
('neg_1024.jpg', 'neg_1024.txt')
('neg_1025.jpg', 'neg_1025

('pos_1427.jpg', 'pos_1427.txt')
('pos_1428.jpg', 'pos_1428.txt')
('pos_1429.jpg', 'pos_1429.txt')
('pos_143.jpg', 'pos_143.txt')
('pos_1430.jpg', 'pos_1430.txt')
('pos_1431.jpg', 'pos_1431.txt')
('pos_1432.jpg', 'pos_1432.txt')
('pos_1433.jpg', 'pos_1433.txt')
('pos_1434.jpg', 'pos_1434.txt')
('pos_1435.jpg', 'pos_1435.txt')
('pos_1436.jpg', 'pos_1436.txt')
('pos_1437.jpg', 'pos_1437.txt')
('pos_1438.jpg', 'pos_1438.txt')
('pos_1439.jpg', 'pos_1439.txt')
('pos_144.jpg', 'pos_144.txt')
('pos_1440.jpg', 'pos_1440.txt')
('pos_1441.jpg', 'pos_1441.txt')
('pos_1442.jpg', 'pos_1442.txt')
('pos_1443.jpg', 'pos_1443.txt')
('pos_1444.jpg', 'pos_1444.txt')
('pos_1445.jpg', 'pos_1445.txt')
('pos_1446.jpg', 'pos_1446.txt')
('pos_1447.jpg', 'pos_1447.txt')
('pos_1448.jpg', 'pos_1448.txt')
('pos_1449.jpg', 'pos_1449.txt')
('pos_145.jpg', 'pos_145.txt')
('pos_1450.jpg', 'pos_1450.txt')
('pos_1451.jpg', 'pos_1451.txt')
('pos_1452.jpg', 'pos_1452.txt')
('pos_1453.jpg', 'pos_1453.txt')
('pos_1454.jpg',

('pos_81.jpg', 'pos_81.txt')
('pos_810.jpg', 'pos_810.txt')
('pos_811.jpg', 'pos_811.txt')
('pos_812.jpg', 'pos_812.txt')
('pos_813.jpg', 'pos_813.txt')
('pos_814.jpg', 'pos_814.txt')
('pos_815.jpg', 'pos_815.txt')
('pos_816.jpg', 'pos_816.txt')
('pos_817.jpg', 'pos_817.txt')
('pos_818.jpg', 'pos_818.txt')
('pos_819.jpg', 'pos_819.txt')
('pos_82.jpg', 'pos_82.txt')
('pos_820.jpg', 'pos_820.txt')
('pos_821.jpg', 'pos_821.txt')
('pos_822.jpg', 'pos_822.txt')
('pos_823.jpg', 'pos_823.txt')
('pos_824.jpg', 'pos_824.txt')
('pos_825.jpg', 'pos_825.txt')
('pos_826.jpg', 'pos_826.txt')
('pos_827.jpg', 'pos_827.txt')
('pos_828.jpg', 'pos_828.txt')
('pos_829.jpg', 'pos_829.txt')
('pos_83.jpg', 'pos_83.txt')
('pos_830.jpg', 'pos_830.txt')
('pos_831.jpg', 'pos_831.txt')
('pos_832.jpg', 'pos_832.txt')
('pos_833.jpg', 'pos_833.txt')
('pos_834.jpg', 'pos_834.txt')
('pos_835.jpg', 'pos_835.txt')
('pos_836.jpg', 'pos_836.txt')
('pos_837.jpg', 'pos_837.txt')
('pos_838.jpg', 'pos_838.txt')
('pos_839.jpg'

In [15]:
# Rename files to match all image/label name formats
for i in range(len(image_files)):
    old_image_file = DATASET + 'obj/' + image_files[i][:-4] + '.jpg'
    new_image_file = DATASET + 'obj/' + 'frame-' + str(i).zfill(3) + '.jpg'
    try:
        os.rename(old_image_file, new_image_file)
    except:
        continue
        
for i in range(len(label_files)):
    old_text_file = DATASET + 'obj/' + label_files[i][:-4] + '.txt'
    new_text_file = DATASET + 'obj/' + 'frame-' + str(i).zfill(3) + '.txt'
    try:
        os.rename(old_text_file, new_text_file)
    except:
        continue
        
# update local variable to keep up with file names
image_files = sorted([x for x in os.listdir(DATASET + 'obj/') if x[-4:] == '.jpg'])
label_files = sorted([x for x in os.listdir(DATASET + 'obj/') if x[-4:] == '.txt'])
for i in zip(image_files, label_files):
    print(i)

('frame-000.jpg', 'frame-000.txt')
('frame-001.jpg', 'frame-001.txt')
('frame-002.jpg', 'frame-002.txt')
('frame-003.jpg', 'frame-003.txt')
('frame-004.jpg', 'frame-004.txt')
('frame-005.jpg', 'frame-005.txt')
('frame-006.jpg', 'frame-006.txt')
('frame-007.jpg', 'frame-007.txt')
('frame-008.jpg', 'frame-008.txt')
('frame-009.jpg', 'frame-009.txt')
('frame-010.jpg', 'frame-010.txt')
('frame-011.jpg', 'frame-011.txt')
('frame-012.jpg', 'frame-012.txt')
('frame-013.jpg', 'frame-013.txt')
('frame-014.jpg', 'frame-014.txt')
('frame-015.jpg', 'frame-015.txt')
('frame-016.jpg', 'frame-016.txt')
('frame-017.jpg', 'frame-017.txt')
('frame-018.jpg', 'frame-018.txt')
('frame-019.jpg', 'frame-019.txt')
('frame-020.jpg', 'frame-020.txt')
('frame-021.jpg', 'frame-021.txt')
('frame-022.jpg', 'frame-022.txt')
('frame-023.jpg', 'frame-023.txt')
('frame-024.jpg', 'frame-024.txt')
('frame-025.jpg', 'frame-025.txt')
('frame-026.jpg', 'frame-026.txt')
('frame-027.jpg', 'frame-027.txt')
('frame-028.jpg', 'f

('frame-700.jpg', 'frame-690.txt')
('frame-701.jpg', 'frame-691.txt')
('frame-702.jpg', 'frame-692.txt')
('frame-703.jpg', 'frame-693.txt')
('frame-704.jpg', 'frame-694.txt')
('frame-705.jpg', 'frame-695.txt')
('frame-706.jpg', 'frame-696.txt')
('frame-707.jpg', 'frame-697.txt')
('frame-708.jpg', 'frame-698.txt')
('frame-709.jpg', 'frame-699.txt')
('frame-710.jpg', 'frame-700.txt')
('frame-711.jpg', 'frame-701.txt')
('frame-712.jpg', 'frame-702.txt')
('frame-713.jpg', 'frame-703.txt')
('frame-714.jpg', 'frame-704.txt')
('frame-715.jpg', 'frame-705.txt')
('frame-716.jpg', 'frame-706.txt')
('frame-717.jpg', 'frame-707.txt')
('frame-718.jpg', 'frame-708.txt')
('frame-719.jpg', 'frame-709.txt')
('frame-720.jpg', 'frame-710.txt')
('frame-721.jpg', 'frame-711.txt')
('frame-722.jpg', 'frame-712.txt')
('frame-723.jpg', 'frame-713.txt')
('frame-724.jpg', 'frame-714.txt')
('frame-725.jpg', 'frame-715.txt')
('frame-726.jpg', 'frame-716.txt')
('frame-727.jpg', 'frame-717.txt')
('frame-728.jpg', 'f

In [16]:
# Add one row for each label
# For each image
temp = []
for file in label_files:
    try:
        image_file =  file[:-4] + '.jpg'
        with open(DATASET + 'obj/' + file, encoding='utf-8') as f:
            for line in f.readlines():
                temp.append([item for item in line.strip('\n').split(' ')] + [image_file])
    except:
        continue
metadata = pd.DataFrame(temp, columns=YOLO_ORDER)
print('metadata created')

metadata created


In [17]:
image_file = metadata.loc[0]['image']
image = cv2.imread(DATASET + 'obj/' + image_file)
print(image)

[[[ 27  44  35]
  [ 24  41  32]
  [ 23  40  29]
  ...
  [ 14  17  15]
  [ 13  16  14]
  [ 12  15  13]]

 [[ 25  42  33]
  [ 22  39  30]
  [ 24  41  30]
  ...
  [ 14  17  15]
  [ 13  16  14]
  [ 12  15  13]]

 [[ 24  40  29]
  [ 15  31  20]
  [ 18  34  23]
  ...
  [ 14  17  15]
  [ 13  16  14]
  [ 12  15  13]]

 ...

 [[147 142 139]
  [103 100  95]
  [113 113 107]
  ...
  [ 71  44  30]
  [ 71  45  29]
  [ 71  45  29]]

 [[205 200 199]
  [192 189 185]
  [196 197 193]
  ...
  [ 71  44  30]
  [ 71  45  29]
  [ 71  45  29]]

 [[255 250 249]
  [246 242 241]
  [226 227 225]
  ...
  [ 71  44  30]
  [ 71  45  29]
  [ 70  44  28]]]


In [18]:
# Convert integer category label to object name string
metadata.loc[metadata['label'] == '0', 'label'] = 'Hard Hat'
metadata.loc[metadata['label'] == '1', 'label'] = 'Safety Vest'

In [19]:
# Convert string coordinates to float coordinates
metadata['x'] = metadata['x'].astype(float)
metadata['y'] = metadata['y'].astype(float)
metadata['w'] = metadata['w'].astype(float)
metadata['h'] = metadata['h'].astype(float)

In [ ]:
for image_file in image_files:
    image = cv2.imread(DATASET + 'obj/' + image_file)
    h, w = image.shape[:2]
    metadata.loc[metadata['image'] == image_file, ['x', 'w']] *= w
    metadata.loc[metadata['image'] == image_file, ['y', 'h']] *= h

In [ ]:
metadata

In [ ]:
metadata['xmin'] = metadata['x'] - metadata['w']/2
metadata['ymin'] = metadata['y'] - metadata['h']/2
metadata['xmax'] = metadata['x'] + metadata['w']/2
metadata['ymax'] = metadata['y'] + metadata['h']/2

In [ ]:
# Convert float coordinates to int coordinates
metadata['xmin'] = metadata['xmin'].astype(int)
metadata['ymin'] = metadata['ymin'].astype(int)
metadata['xmax'] = metadata['xmax'].astype(int)
metadata['ymax'] = metadata['ymax'].astype(int)

In [ ]:
# Drop unused columns
metadata = metadata[APP_ORDER]

In [ ]:
# Check that coordinates fit within image size
metadata[metadata['image'] == 'pos_1003.jpg']

In [ ]:
# Stop "Run All" execution before saving file
assert False

In [ ]:
# Save file
metadata.to_csv(METADATA_FILE, index=False)